package MotorPHGUI;

import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author trisha
 */
public class NewEmployee extends javax.swing.JFrame {

    /**
     * Creates new form NewEmployee
     */
    public NewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pstncompbox = new javax.swing.JComboBox<>();
        StatusProbtn = new javax.swing.JRadioButton();
        jRadioBegutton2 = new javax.swing.JRadioButton();
        lstnametxt = new javax.swing.JTextField();
        frstnametxt = new javax.swing.JTextField();
        lstnamelbl = new javax.swing.JLabel();
        FrstNamelbl = new javax.swing.JLabel();
        Bdaylbl = new javax.swing.JLabel();
        bdaytxt = new javax.swing.JTextField();
        Adresslbl = new javax.swing.JLabel();
        adresstxt = new javax.swing.JTextField();
        Philnumbertxt = new javax.swing.JTextField();
        Phnumberlbl = new javax.swing.JLabel();
        SSSnumberlbl = new javax.swing.JLabel();
        Philhealthlbl = new javax.swing.JLabel();
        phnumbertxt = new javax.swing.JTextField();
        ssstxt = new javax.swing.JTextField();
        Pagibiglbl = new javax.swing.JLabel();
        TinLbl = new javax.swing.JLabel();
        pagibigtxt = new javax.swing.JTextField();
        Tintxt = new javax.swing.JTextField();
        Statslbl = new javax.swing.JLabel();
        Posistionlbl = new javax.swing.JLabel();
        supervisorcombobox = new javax.swing.JComboBox<>();
        Supervisorlbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        submitbtn = new javax.swing.JButton();
        basicSalaryLbl = new javax.swing.JLabel();
        riceSubsidyLbl = new javax.swing.JLabel();
        phoneAllowanceLbl = new javax.swing.JLabel();
        clothingAllowanceLbl = new javax.swing.JLabel();
        grossSemiMonthlyLbl = new javax.swing.JLabel();
        hourlyRateLbl = new javax.swing.JLabel();
        basicSalaryTxt = new javax.swing.JTextField();
        riceSubsidyTxt = new javax.swing.JTextField();
        phoneAllowanceTxt = new javax.swing.JTextField();
        clothingAllowanceTxt = new javax.swing.JTextField();
        grossSemiMonthlyTxt = new javax.swing.JTextField();
        hourlyRateTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pstncompbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chief Executive Officer", "Chief Operating Officer", "Chief Finance Officer", "Chief Marketing Officer", "IT Operations and Systems", "HR Manager", "HR Team Leader", "HR Rank and File", "Accounting Head", "Payroll Manager", "Payroll Team Leader", "Payroll Rank and File", "Account Manager", "Account Team Leader", "Account Rank and File", "Sales & Marketing", "Supply Chain and Logistics", "Customer Service and Relations" }));
        pstncompbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pstncompboxActionPerformed(evt);
            }
        });

        StatusProbtn.setText("Probitionary");
        StatusProbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusProbtnActionPerformed(evt);
            }
        });

        jRadioBegutton2.setText("Regular");
        jRadioBegutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBegutton2ActionPerformed(evt);
            }
        });

        lstnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstnametxtActionPerformed(evt);
            }
        });

        frstnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frstnametxtActionPerformed(evt);
            }
        });

        lstnamelbl.setText("Last Name");

        FrstNamelbl.setText("First Name");

        Bdaylbl.setText("Birthday");

        bdaytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdaytxtActionPerformed(evt);
            }
        });

        Adresslbl.setText("Adress");

        adresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresstxtActionPerformed(evt);
            }
        });

        Philnumbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhilnumbertxtActionPerformed(evt);
            }
        });

        Phnumberlbl.setText("Phone Number");

        SSSnumberlbl.setText("SSS Number");

        Philhealthlbl.setText("PhilHealh Number");

        phnumbertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnumbertxtActionPerformed(evt);
            }
        });

        ssstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssstxtActionPerformed(evt);
            }
        });

        Pagibiglbl.setText("Pag-ibig Number");

        TinLbl.setText("TIN Number");

        pagibigtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibigtxtActionPerformed(evt);
            }
        });

        Tintxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TintxtActionPerformed(evt);
            }
        });

        Statslbl.setText("Status");

        Posistionlbl.setText("Posistion");

        supervisorcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Garcia, Manuel III", "Villanueva, Andrea Mae", "San, Jose Brad", "Aquino, Bianca Sofia ", "Alvaro, Roderick", "Salcedo, Anthony", "Lim, Antonio", "Romualdez, Fredrick ", "Mata, Christian", "De Leon, Selena", "Reyes, Isabella", " ", " " }));
        supervisorcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisorcomboboxActionPerformed(evt);
            }
        });

        Supervisorlbl.setText("Supervisor");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel11.setText("MOTORPH EMPLOYEE NEW EMPLOYEE INFORMATION");

        submitbtn.setLabel("SUBMIT");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        basicSalaryLbl.setText("Basic Salary");
        basicSalaryLbl.setVisible(false);

        riceSubsidyLbl.setText("Rice Subsidy");
        riceSubsidyLbl.setVisible(false);

        phoneAllowanceLbl.setText("Phone Allowance");
        phoneAllowanceLbl.setVisible(false);

        clothingAllowanceLbl.setText("Clothing Allowance");
        clothingAllowanceLbl.setVisible(false);

        grossSemiMonthlyLbl.setText("Gross Semi-monthly");
        grossSemiMonthlyLbl.setVisible(false);

        hourlyRateLbl.setText("Hourly Rate");
        hourlyRateLbl.setVisible(false);

        basicSalaryTxt.setEditable(false);
        basicSalaryTxt.setVisible(false);

        riceSubsidyTxt.setEditable(false);
        riceSubsidyTxt.setVisible(false);

        phoneAllowanceTxt.setEditable(false);
        phoneAllowanceTxt.setVisible(false);

        clothingAllowanceTxt.setEditable(false);
        clothingAllowanceTxt.setVisible(false);

        grossSemiMonthlyTxt.setEditable(false);
        grossSemiMonthlyTxt.setVisible(false);

        hourlyRateTxt.setEditable(false);
        hourlyRateTxt.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Phnumberlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SSSnumberlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Philhealthlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lstnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FrstNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Bdaylbl)
                                            .addComponent(Adresslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Pagibiglbl)
                                    .addComponent(TinLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Supervisorlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Statslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Posistionlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supervisorcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lstnametxt)
                                .addComponent(jRadioBegutton2)
                                .addComponent(StatusProbtn)
                                .addComponent(pstncompbox, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bdaytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phnumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Philnumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pagibigtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(basicSalaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(riceSubsidyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneAllowanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clothingAllowanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grossSemiMonthlyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hourlyRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(basicSalaryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riceSubsidyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneAllowanceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clothingAllowanceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grossSemiMonthlyLbl)
                    .addComponent(hourlyRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstnamelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrstNamelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdaytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bdaylbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adresslbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phnumberlbl)
                    .addComponent(phnumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSSnumberlbl)
                    .addComponent(ssstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Philhealthlbl)
                    .addComponent(Philnumbertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TinLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagibigtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pagibiglbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Statslbl)
                    .addComponent(StatusProbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioBegutton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pstncompbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Posistionlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supervisorcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Supervisorlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicSalaryLbl)
                    .addComponent(basicSalaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(riceSubsidyLbl)
                    .addComponent(riceSubsidyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneAllowanceLbl)
                    .addComponent(phoneAllowanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clothingAllowanceLbl)
                    .addComponent(clothingAllowanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossSemiMonthlyLbl)
                    .addComponent(grossSemiMonthlyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourlyRateLbl)
                    .addComponent(hourlyRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(submitbtn)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>                        

    private void pstncompboxActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        updateSalaryFields();
    }                                           

    private void StatusProbtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jRadioBegutton2ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void lstnametxtActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void frstnametxtActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void bdaytxtActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void adresstxtActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void PhilnumbertxtActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void phnumbertxtActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void ssstxtActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void pagibigtxtActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void TintxtActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void supervisorcomboboxActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (validateAllFields()) {
            if (saveEmployee()) {
                JOptionPane.showMessageDialog(this, "Employee added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearAllFields();
            }
        }
    }

    private boolean validateAllFields() {
        // Validate Last Name
        if (lstnametxt.getText().trim().isEmpty()) {
            showError("Last Name is required.");
            lstnametxt.requestFocus();
            return false;
        }

        // Validate First Name
        if (frstnametxt.getText().trim().isEmpty()) {
            showError("First Name is required.");
            frstnametxt.requestFocus();
            return false;
        }

        // Validate Birthday format
        if (!isValidDate(bdaytxt.getText().trim())) {
            showError("Birthday must be in MM/DD/YYYY format.");
            bdaytxt.requestFocus();
            return false;
        }

        // Validate Address
        if (adresstxt.getText().trim().isEmpty()) {
            showError("Address is required.");
            adresstxt.requestFocus();
            return false;
        }

        // Validate Phone Number format
        if (!isValidPhoneNumber(phnumbertxt.getText().trim())) {
            showError("Phone Number must be in XXX-XXX-XXX format.");
            phnumbertxt.requestFocus();
            return false;
        }

        // Validate SSS Number format
        if (!isValidSSSNumber(ssstxt.getText().trim())) {
            showError("SSS Number must be in XX-XXXXXXX-X format.");
            ssstxt.requestFocus();
            return false;
        }

        // Validate PhilHealth Number
        if (!isValidPhilHealthNumber(Philnumbertxt.getText().trim())) {
            showError("PhilHealth Number must be 12 digits.");
            Philnumbertxt.requestFocus();
            return false;
        }

        // Validate TIN Number format
        if (!isValidTINNumber(Tintxt.getText().trim())) {
            showError("TIN Number must be in XXX-XXX-XXX-XXX format.");
            Tintxt.requestFocus();
            return false;
        }

        // Validate Pag-ibig Number format
        if (!isValidPagibigNumber(pagibigtxt.getText().trim())) {
            showError("Pag-ibig Number must be 12 digits.");
            pagibigtxt.requestFocus();
            return false;
        }

        // Validate Status selection
        if (!StatusProbtn.isSelected() && !jRadioBegutton2.isSelected()) {
            showError("Please select employment status (Probationary or Regular).");
            return false;
        }

        // Check for duplicate SSS, PhilHealth, TIN, and Pag-ibig numbers
        if (isDuplicate()) {
            return false;
        }

        return true;
    }

    private boolean isValidDate(String date) {
        if (date.isEmpty()) return false;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            sdf.setLenient(false);
            sdf.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

    private boolean isValidPhoneNumber(String phone) {
        if (phone.isEmpty()) return false;
        return Pattern.matches("\\d{3}-\\d{3}-\\d{3}", phone);
    }

    private boolean isValidSSSNumber(String sss) {
        if (sss.isEmpty()) return false;
        return Pattern.matches("\\d{2}-\\d{7}-\\d{1}", sss);
    }

    private boolean isValidPhilHealthNumber(String philhealth) {
        if (philhealth.isEmpty()) return false;
        return Pattern.matches("\\d{12}", philhealth);
    }

    private boolean isValidTINNumber(String tin) {
        if (tin.isEmpty()) return false;
        return Pattern.matches("\\d{3}-\\d{3}-\\d{3}-\\d{3}", tin);
    }

    private boolean isValidPagibigNumber(String pagibig) {
        if (pagibig.isEmpty()) return false;
        return Pattern.matches("\\d{12}", pagibig);
    }

    private boolean isDuplicate() {
        String sssInput = ssstxt.getText().trim();
        String philhealthInput = Philnumbertxt.getText().trim();
        String tinInput = Tintxt.getText().trim();
        String pagibigInput = pagibigtxt.getText().trim();

        // Check SSS Number (index 8)
        if (EmployeeUtil.valueExistsInColumn("Emp_Details.csv", 8, sssInput, true)) {
            showError("SSS Number already exists in the system.");
            ssstxt.requestFocus();
            return true;
        }

        // Check PhilHealth Number (index 9)
        if (EmployeeUtil.valueExistsInColumn("Emp_Details.csv", 9, philhealthInput, true)) {
            showError("PhilHealth Number already exists in the system.");
            Philnumbertxt.requestFocus();
            return true;
        }

        // Check TIN Number (index 10)
        if (EmployeeUtil.valueExistsInColumn("Emp_Details.csv", 10, tinInput, true)) {
            showError("TIN Number already exists in the system.");
            Tintxt.requestFocus();
            return true;
        }

        // Check Pag-ibig Number (index 11)
        if (EmployeeUtil.valueExistsInColumn("Emp_Details.csv", 11, pagibigInput, true)) {
            showError("Pag-ibig Number already exists in the system.");
            pagibigtxt.requestFocus();
            return true;
        }

        return false;
    }

    private boolean saveEmployee() {
        try {
            // Generate new employee ID
            int newEmployeeId = EmployeeUtil.getNextEmployeeId("Emp_Details.csv");

            // Get status
            String status = StatusProbtn.isSelected() ? "Probationary" : "Regular";

            // Get position
            String position = (String) pstncompbox.getSelectedItem();

            // Get supervisor
            String supervisor = (String) supervisorcombobox.getSelectedItem();

            //Get Salary Values
            String basicSalary = basicSalaryTxt.getText().trim();
            String riceSub = riceSubsidyTxt.getText().trim();
            String phoneAll = phoneAllowanceTxt.getText().trim();
            String clothingAll = clothingAllowanceTxt.getText().trim();
            String grossSemi = grossSemiMonthlyTxt.getText().trim();
            String hourlyR = hourlyRateTxt.getText().trim();

            // Create new employee row
            String[] newEmployeeRow = {
                String.valueOf(newEmployeeId),
                lstnametxt.getText().trim(),
                frstnametxt.getText().trim(),
                bdaytxt.getText().trim(),
                basicSalary, // Basic Salary
                hourlyR, // Hourly Rate
                adresstxt.getText().trim(),
                phnumbertxt.getText().trim(),
                ssstxt.getText().trim(),
                Philnumbertxt.getText().trim(),
                Tintxt.getText().trim(),
                pagibigtxt.getText().trim(),
                status,
                position,
                supervisor,
                riceSub, // Rice Subsidy
                phoneAll, // Phone Allowance
                clothingAll, // Clothing Allowance
                grossSemi  // Gross Semi-monthly Rate
            };

            // Append to CSV file using utility
            EmployeeUtil.appendCSVRow("Emp_Details.csv", newEmployeeRow);

            return true;
        } catch (IOException e) {
            showError("Error saving employee data: " + e.getMessage());
            return false;
        }
    }

    private void updateSalaryFields() {
        String position = (String) pstncompbox.getSelectedItem();
        double basicSalary, riceSubsidy, phoneAllowance, clothingAllowance, grossSemiMonthly, hourlyRate;

        switch (position) {
            case "Chief Executive Officer":
                basicSalary = 150000.00;
                riceSubsidy = 2000.00;
                phoneAllowance = 1500.00;
                clothingAllowance = 5000.00;
                break;
            case "Chief Operating Officer":
                basicSalary = 130000.00;
                riceSubsidy = 2000.00;
                phoneAllowance = 1500.00;
                clothingAllowance = 5000.00;
                break;
            case "Chief Finance Officer":
                basicSalary = 120000.00;
                riceSubsidy = 2000.00;
                phoneAllowance = 1500.00;
                clothingAllowance = 5000.00;
                break;
            case "Chief Marketing Officer":
                basicSalary = 110000.00;
                riceSubsidy = 2000.00;
                phoneAllowance = 1500.00;
                clothingAllowance = 5000.00;
                break;
            case "IT Operations and Systems":
                basicSalary = 90000.00;
                riceSubsidy = 1500.00;
                phoneAllowance = 1000.00;
                clothingAllowance = 3000.00;
                break;
            case "HR Manager":
                basicSalary = 80000.00;
                riceSubsidy = 1500.00;
                phoneAllowance = 1000.00;
                clothingAllowance = 3000.00;
                break;
            case "HR Team Leader":
                basicSalary = 60000.00;
                riceSubsidy = 1000.00;
                phoneAllowance = 750.00;
                clothingAllowance = 2000.00;
                break;
            case "HR Rank and File":
                basicSalary = 40000.00;
                riceSubsidy = 1000.00;
                phoneAllowance = 500.00;
                clothingAllowance = 1500.00;
                break;
            case "Accounting Head":
                basicSalary = 75000.00;
                riceSubsidy = 1500.00;
                phoneAllowance = 1000.00;
                clothingAllowance = 3000.00;
                break;
            case "Payroll Manager":
                basicSalary = 70000.00;
                riceSubsidy = 1500.00;
                phoneAllowance = 1000.00;
                clothingAllowance = 3000.00;
                break;
            case "Payroll Team Leader":
                basicSalary = 55000.00;
                riceSubsidy = 1000.00;
                phoneAllowance = 750.00;
                clothingAllowance = 2000.00;
                break;
            case "Payroll Rank and File":
                basicSalary = 35000.00;
                riceSubsidy = 1000.00;
                phoneAllowance = 500.00;
                clothingAllowance = 1500.00;
                break;
            case "Account Manager":
                basicSalary = 65000.00;
                riceSubsidy = 1000.00;
                phoneAllowance = 750.00;
                clothingAllowance = 2000.00;
                break;
            case "Account Team Leader":
                basicSalary = 50000.00;
                riceSubsidy = 1000.00;
                phoneAllowance = 750.00;
                clothingAllowance = 2000.00;
                break;
            case "Account Rank and File":
                basicSalary = 30000.00;
                riceSubsidy = 1000.00;
                phoneAllowance = 500.00;
                clothingAllowance = 1500.00;
                break;
            case "Sales & Marketing":
                basicSalary = 60000.00;
                riceSubsidy = 1000.00;
                phoneAllowance = 750.00;
                clothingAllowance = 2000.00;
                break;
            case "Supply Chain and Logistics":
                basicSalary = 55000.00;
                riceSubsidy = 1000.00;
                phoneAllowance = 750.00;
                clothingAllowance = 2000.00;
                break;
            case "Customer Service and Relations":
                basicSalary = 45000.00;
                riceSubsidy = 1000.00;
                phoneAllowance = 500.00;
                clothingAllowance = 1500.00;
                break;
            default:
                basicSalary = 25000.00;
                riceSubsidy = 500.00;
                phoneAllowance = 250.00;
                clothingAllowance = 1000.00;
                break;
        }

        grossSemiMonthly = (basicSalary + riceSubsidy + phoneAllowance + clothingAllowance) / 2;
        hourlyRate = basicSalary / 160; // Assuming 160 hours per month

        basicSalaryTxt.setText(String.format("%.2f", basicSalary));
        riceSubsidyTxt.setText(String.format("%.2f", riceSubsidy));
        phoneAllowanceTxt.setText(String.format("%.2f", phoneAllowance));
        clothingAllowanceTxt.setText(String.format("%.2f", clothingAllowance));
        grossSemiMonthlyTxt.setText(String.format("%.2f", grossSemiMonthly));
        hourlyRateTxt.setText(String.format("%.2f", hourlyRate));
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Validation Error", JOptionPane.ERROR_MESSAGE);
    }

    private void clearAllFields() {
        lstnametxt.setText("");
        frstnametxt.setText("");
        bdaytxt.setText("");
        adresstxt.setText("");
        phnumbertxt.setText("");
        ssstxt.setText("");
        Philnumbertxt.setText("");
        Tintxt.setText("");
        pagibigtxt.setText("");
        StatusProbtn.setSelected(false);
        jRadioBegutton2.setSelected(false);
        pstncompbox.setSelectedIndex(0);
        supervisorcombobox.setSelectedIndex(0);
        basicSalaryTxt.setText("");
        riceSubsidyTxt.setText("");
        phoneAllowanceTxt.setText("");
        clothingAllowanceTxt.setText("");
        grossSemiMonthlyTxt.setText("");
        hourlyRateTxt.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Adresslbl;
    private javax.swing.JLabel Bdaylbl;
    private javax.swing.JLabel FrstNamelbl;
    private javax.swing.JLabel Pagibiglbl;
    private javax.swing.JLabel Philhealthlbl;
    private javax.swing.JTextField Philnumbertxt;
    private javax.swing.JLabel Phnumberlbl;
    private javax.swing.JLabel Posistionlbl;
    private javax.swing.JLabel SSSnumberlbl;
    private javax.swing.JLabel Statslbl;
    private javax.swing.JRadioButton StatusProbtn;
    private javax.swing.JLabel Supervisorlbl;
    private javax.swing.JLabel TinLbl;
    private javax.swing.JTextField Tintxt;
    private javax.swing.JTextField adresstxt;
    private javax.swing.JLabel basicSalaryLbl;
    private javax.swing.JTextField basicSalaryTxt;
    private javax.swing.JTextField bdaytxt;
    private javax.swing.JLabel clothingAllowanceLbl;
    private javax.swing.JTextField clothingAllowanceTxt;
    private javax.swing.JTextField frstnametxt;
    private javax.swing.JLabel grossSemiMonthlyLbl;
    private javax.swing.JTextField grossSemiMonthlyTxt;
    private javax.swing.JLabel hourlyRateLbl;
    private javax.swing.JTextField hourlyRateTxt;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JRadioButton jRadioBegutton2;
    private javax.swing.JLabel lstnamelbl;
    private javax.swing.JTextField lstnametxt;
    private javax.swing.JTextField pagibigtxt;
    private javax.swing.JTextField phnumbertxt;
    private javax.swing.JLabel phoneAllowanceLbl;
    private javax.swing.JTextField phoneAllowanceTxt;
    private javax.swing.JComboBox<String> pstncompbox;
    private javax.swing.JLabel riceSubsidyLbl;
    private javax.swing.JTextField riceSubsidyTxt;
    private javax.swing.JTextField ssstxt;
    private javax.swing.JButton submitbtn;
    private javax.swing.JComboBox<String> supervisorcombobox;
    // End of variables declaration                   
}