
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author trisha
 */
public class LoginJava extends javax.swing.JFrame {

    /**
     * Creates new form LoginJava
     */
    public LoginJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jDialog1 = new javax.swing.JDialog();
        LBLPEND = new javax.swing.JLabel();
        submitbut = new javax.swing.JButton();
        LBLIDNUM = new javax.swing.JLabel();
        txtIDNUM = new javax.swing.JTextField();
        LBLPSTART = new javax.swing.JLabel();
        txtpayend = new javax.swing.JTextField();
        MOTORPHPAYROLL = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        txtpaystart = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLPEND.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LBLPEND.setText("Pay Period End");

        submitbut.setBackground(new java.awt.Color(255, 51, 102));
        submitbut.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        submitbut.setForeground(new java.awt.Color(255, 255, 255));
        submitbut.setText("Submit");
        submitbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbutActionPerformed(evt);
            }
        });

        LBLIDNUM.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LBLIDNUM.setText("ID NUMBER");

        txtIDNUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDNUMActionPerformed(evt);
            }
        });

        LBLPSTART.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LBLPSTART.setText("Pay Period Start");

        txtpayend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpayendActionPerformed(evt);
            }
        });

        MOTORPHPAYROLL.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        MOTORPHPAYROLL.setText("MOTORPH PAYROLL SYSTEM");

        Login.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Login.setText("LOGIN ");

        txtpaystart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaystartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(MOTORPHPAYROLL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LBLPSTART, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLPEND, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBLIDNUM, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpayend, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitbut)
                            .addComponent(txtIDNUM, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpaystart, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(MOTORPHPAYROLL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBLIDNUM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIDNUM)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBLPSTART, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpaystart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLPEND, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpayend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitbut)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbutActionPerformed
     try {
        String employeeId = txtIDNUM.getText();
        LocalDate startDate = LocalDate.parse(txtpaystart.getText(), 
            DateTimeFormatter.ofPattern("MM/dd/yyyy"));
        LocalDate endDate = LocalDate.parse(txtpayend.getText(), 
            DateTimeFormatter.ofPattern("MM/dd/yyyy"));

        // Get attendance records
        List<TimeInandOut.AttendanceRecord> records = 
            TimeInandOut.readAttendanceRecords(employeeId, startDate, endDate);

        // Create results panel
        JPanel resultsPanel = new JPanel();
        resultsPanel.setLayout(new BoxLayout(resultsPanel, BoxLayout.Y_AXIS));
        resultsPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Create text area for results
        JTextArea resultsArea = new JTextArea();
        resultsArea.setEditable(false);
        resultsArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        
        // Calculate totals
        double totalHours = 0;
        double totalPenalties = 0;
        for (TimeInandOuts.AttendanceRecord record : records) {
            totalHours += record.calculateHours();
            totalPenalties += record.calculateLatePenalty();
        }

        // Format and display results
        StringBuilder sb = new StringBuilder();
        sb.append("========== PAYROLL SUMMARY ==========\n\n");
        sb.append(String.format("Employee ID: %s\n", employeeId));
        sb.append(String.format("Period: %s to %s\n\n", 
            startDate.format(DateTimeFormatter.ofPattern("MM/dd/yyyy")),
            endDate.format(DateTimeFormatter.ofPattern("MM/dd/yyyy"))));
        
        sb.append("Attendance Summary:\n");
        sb.append(String.format("Total Hours: %.2f\n", totalHours));
        sb.append(String.format("Late Penalties: ₱%,.2f\n\n", totalPenalties));

        // Calculate salary and deductions
        Employee employee = findEmployee(employeeId); // Implement this method
        if (employee != null) {
            employee.calculateDeductions();
            employee.calculateWeeklySalary(totalHours);
            
            sb.append("Salary Details:\n");
            sb.append(String.format("Basic Salary: ₱%,.2f\n", employee.getBasicSalary()));
            sb.append(String.format("Hourly Rate: ₱%,.2f\n\n", employee.getHourlyRate()));
            
            sb.append("Deductions:\n");
            sb.append(String.format("Pag-IBIG: ₱%,.2f\n", employee.getPagIbigContribution()));
            sb.append(String.format("PhilHealth: ₱%,.2f\n", employee.getPhilHealthContribution()));
            sb.append(String.format("SSS: ₱%,.2f\n", employee.getSSS()));
            sb.append(String.format("Total Deductions: ₱%,.2f\n\n", employee.getTotalDeductions()));
            
            sb.append("Final Computation:\n");
            sb.append(String.format("Gross Pay: ₱%,.2f\n", totalHours * employee.getHourlyRate()));
            sb.append(String.format("Net Pay: ₱%,.2f\n", 
                (totalHours * employee.getHourlyRate()) - totalPenalties - employee.getTotalDeductions()));
        }
        
        sb.append("\n=====================================");
        resultsArea.setText(sb.toString());
        
        // Add to scroll pane
        JScrollPane scrollPane = new JScrollPane(resultsArea);
        scrollPane.setPreferredSize(new Dimension(400, 500));
        
        // Add to results panel
        resultsPanel.add(scrollPane);
        
        // Update the display
        resultsPanel.revalidate();
        resultsPanel.repaint();
        
        // Add to the main frame
        getContentPane().removeAll();
        getContentPane().add(resultsPanel);
        pack();
        setLocationRelativeTo(null);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error calculating payroll: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    }//GEN-LAST:event_submitbutActionPerformed
  
    private void txtIDNUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDNUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDNUMActionPerformed

    private void txtpayendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpayendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayendActionPerformed

    private void txtpaystartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaystartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaystartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLIDNUM;
    private javax.swing.JLabel LBLPEND;
    private javax.swing.JLabel LBLPSTART;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel MOTORPHPAYROLL;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton submitbut;
    private javax.swing.JTextField txtIDNUM;
    private javax.swing.JTextField txtpayend;
    private javax.swing.JTextField txtpaystart;
    // End of variables declaration//GEN-END:variables
}
